services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    environment:
      DB_HOST: db
      STORED_DOCUMENTS_DIR: /app/stored_documents
    volumes:
      - stored_documents:/app/stored_documents
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: handy_tools_db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d handy_tools_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - frontend/.env.example
  #   depends_on:
  #     - backend

volumes:
  postgres_data:
  stored_documents:

networks:
  backend:
    driver: bridge